"""Build reproducible store artwork from the extension's real HTML and CSS.

Demo fixtures supply example answers; no API keys or network calls are used.
Capture each #asset in Aside, then export as RGB PNG for Chrome Web Store.
"""
from pathlib import Path
import json
import zipfile

ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / 'store-assets'
WEB = OUT / 'source' / 'web'
WEB.mkdir(exist_ok=True)
for name in ['models.js', 'popup.js', 'content.js', 'styles.css']:
    (WEB / name).write_text((ROOT / name).read_text())

stub = '''<script>
// Isolated screenshot fixture: empty local settings, no credentials or requests.
const chrome = {storage:{local:{get:(names,cb)=>cb?cb({}):Promise.resolve({}),
set:()=>Promise.resolve(),remove:()=>Promise.resolve()}},runtime:{
sendMessage:(msg,cb)=>cb&&cb({models:[],errors:[]}),lastError:null}};
window.addEventListener('load',()=>document.getElementById('toggleViewBtn').click());
</script>'''
popup = (ROOT / 'popup.html').read_text().replace('<script src="models.js">', stub + '<script src="models.js">')
(WEB / 'settings.html').write_text(popup)

quiz = '''<!doctype html><html><head><meta charset="utf-8"><link rel="stylesheet" href="styles.css"><style>
*{box-sizing:border-box}body{margin:0;font-family:Arial,sans-serif;background:#f8f9fc;color:#202739}
.bar{padding:18px 22px;border-bottom:1px solid #e5e7ef;display:flex;justify-content:space-between;font-size:11px;color:#687086;font-weight:bold;letter-spacing:1.1px}
h1{text-align:center;font-size:29px;line-height:1.3;margin:35px 20px 28px;letter-spacing:-.5px}
.answers{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin:0 22px}.option{padding:23px;border-radius:9px;color:white;font-weight:bold;font-size:23px;display:flex;gap:19px;align-items:center}
.red{background:#de294c}.blue{background:#256fd2}.yellow{background:#bb8200}.green{background:#278839}
.note{margin:19px 22px;font-size:11px;color:#7c8395}.option span{font-size:22px}
</style><script>window.demoListeners=[];window.chrome={runtime:{onMessage:{addListener:fn=>demoListeners.push(fn)}}};</script></head><body>
<div class="bar"><span>PRACTICE QUIZ</span><span>QUESTION 01 / 05</span></div><h1>Which planet is known<br>as the Red Planet?</h1>
<div class="answers"><div class="option red"><span>▲</span>Earth</div><div class="option blue"><span>◆</span>Venus</div><div class="option yellow"><span>●</span>Jupiter</div><div class="option green"><span>■</span>Mars</div></div><div class="note">Demo question · Example answer shown</div>
<script src="content.js"></script><script>
const mode=new URLSearchParams(location.search).get('mode')||'normal';
const emit=()=>demoListeners.forEach(fn=>fn({action:'highlight_answer',mode,answer:'green'}));emit();setInterval(emit,1000);
</script></body></html>'''
(WEB / 'quiz.html').write_text(quiz)

for label, answer in [('multiple', {'type':'multiple','colors':['red','yellow']}), ('text', {'type':'text','text':'Paris'}), ('order', {'type':'order','items':['2','4','6','8']}), ('number', {'type':'number','value':60})]:
    (WEB / (label+'.html')).write_text('''<!doctype html><html><head><meta charset="utf-8"><link rel="stylesheet" href="styles.css"><style>body{margin:0;background:#eff2f8}.kahoot-normal-panel{bottom:18px;right:18px;left:18px;max-height:none;font-size:17px;box-shadow:none}</style><script>window.demoListeners=[];window.chrome={runtime:{onMessage:{addListener:fn=>demoListeners.push(fn)}}};</script></head><body><script src="content.js"></script><script>const emit=()=>demoListeners.forEach(fn=>fn({action:'highlight_answer',mode:'normal',answer:ANSWER}));emit();setInterval(emit,1000);</script></body></html>'''.replace('ANSWER',json.dumps(answer)))

style = '''
*{box-sizing:border-box}html,body{margin:0}body{font-family:-apple-system,BlinkMacSystemFont,'Arial',sans-serif;background:#e9ebf3;color:#1d2440}iframe{border:0;display:block;background:white}
#asset{width:1280px;height:800px;position:relative;overflow:hidden;background:#f6f7fb;padding:44px 56px}
.mast{display:flex;align-items:center;justify-content:space-between;position:relative;z-index:3}.brand{display:flex;align-items:center;gap:14px;font-size:19px;font-weight:730;letter-spacing:-.5px}.mark{background:#202743;border-radius:13px;width:44px;height:44px;display:grid;grid-template-columns:1fr 1fr;place-items:center;padding:9px;gap:4px}.mark i{width:11px;height:11px;display:block}.mark i:nth-child(1){background:#fb627d;clip-path:polygon(50% 0,100% 100%,0 100%)}.mark i:nth-child(2){background:#69abff;transform:rotate(45deg);width:9px;height:9px}.mark i:nth-child(3){background:#ffcf58;border-radius:100%}.mark i:nth-child(4){background:#64d8a4;border-radius:2px}
.tag{font-size:11px;letter-spacing:1.9px;font-weight:700;border:1px solid #d7dbe7;border-radius:100px;padding:10px 16px;color:#6b7185}.eyebrow{font-size:12px;font-weight:750;letter-spacing:2px;color:#6962c1;margin-bottom:21px}.title{font-size:66px;font-weight:780;line-height:1.04;letter-spacing:-3.4px;margin:0}.title span{color:#7267df}.sub{font-size:19px;line-height:1.55;color:#646c84;max-width:425px;margin:24px 0}.footer{position:absolute;bottom:34px;left:56px;right:56px;display:flex;justify-content:space-between;color:#82889c;font-size:12px}.footnum{letter-spacing:2px;font-weight:650}.left{position:absolute;left:56px;top:180px;width:460px}.right{position:absolute;right:44px;top:160px;width:656px}
.dark{background:#202743;color:white;border-radius:25px;padding:24px;box-shadow:0 20px 60px #22294a21}.browser{background:#fff;border-radius:14px;overflow:hidden;border:1px solid #e4e6ef;box-shadow:0 18px 48px #171c3314}.browserbar{height:37px;background:#eef0f5;display:flex;align-items:center;gap:5px;padding:0 13px}.browserbar b{height:7px;width:7px;border-radius:50%;background:#bec5d5}.browserbar small{color:#8891a6;font-size:10px;margin-left:13px}.quizframe{width:100%;height:425px}.darklabel{display:flex;justify-content:space-between;color:#aab2cd;letter-spacing:1.5px;font-size:10px;font-weight:700;margin-bottom:16px}.pill{display:inline-flex;align-items:center;gap:9px;background:white;border:1px solid #e1e4ef;border-radius:9px;padding:12px 16px;font-size:13px;color:#494f69;margin-top:12px}.key{display:inline-flex;background:#202743;color:white;border-radius:7px;font-size:13px;padding:8px 12px;box-shadow:0 3px 0 #11162b;font-weight:650}.legend{display:flex;gap:12px;color:#acb5d1;margin-top:18px;font-size:11px}.legend b{color:#fff}.step{display:flex;gap:15px;align-items:flex-start;margin:22px 0;color:#555e76;font-size:16px;line-height:1.5}.step b{display:block;color:#252d49;font-size:17px;font-weight:700}.stepnum{border:1px solid #d6d8ef;width:32px;height:32px;flex:none;border-radius:10px;color:#7267df;display:grid;place-items:center;font-weight:700;font-size:13px}.nativewrap{width:406px;height:890px;transform:scale(.69);transform-origin:top left}.nativewrap iframe{width:406px;height:890px}.nativebox{width:282px;height:616px;overflow:hidden;border-radius:15px;background:#f7f9fc;border:1px solid #d4d9e6;box-shadow:0 18px 48px #171c3314}.callout{position:absolute;background:#fff;border:1px solid #e0e3ed;border-radius:15px;padding:18px 20px;width:236px;font-size:14px;line-height:1.5;color:#677087}.callout strong{display:block;color:#2a324e;margin-bottom:6px;font-size:16px}.callout:before{content:'';position:absolute;width:35px;height:1px;background:#b6b4de;left:-35px;top:30px}.caption{font-size:11px;color:#81899c;margin-top:15px;line-height:1.5}
.keygrid{display:grid;grid-template-columns:repeat(3,1fr);gap:18px;margin-top:34px}.keycard{padding:24px;background:white;border:1px solid #e0e3ed;border-radius:19px;height:184px}.keycard small{letter-spacing:1.7px;color:#8790a5;font-size:11px;font-weight:700}.keycard .bigkey{font-size:34px;font-weight:750;letter-spacing:-1px;margin-top:20px}.keycard p{color:#6b738a;font-size:14px;margin:13px 0}.modecols{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:22px}.modecols>div{min-width:0}.modetitle{display:flex;justify-content:space-between;font-size:15px;font-weight:700;margin-bottom:15px}.modetitle small{font-size:11px;font-weight:500;color:#7e879e}.modeframe{width:100%;height:355px}.modebrowser{overflow:hidden;border-radius:13px;border:1px solid #dfe3ef}.modebrowser iframe{width:682px;height:425px;transform:scale(.835);transform-origin:top left}.shapes{display:flex;gap:8px;margin-top:16px;justify-content:space-between}.shapes span{font-size:12px;color:#727c92}.formatcard{border:1px solid #dce1ed;border-radius:18px;padding:22px;background:white}.formatcard h3{font-size:20px;margin:0 0 5px;letter-spacing:-.4px}.formatcard p{font-size:13px;margin:0 0 18px;color:#7a839a}.formatcard iframe{height:157px;width:100%;border-radius:11px;background:#eff2f8}.formatgrid{display:grid;grid-template-columns:1fr 1fr;gap:16px}.privacycard{padding:25px;background:white;border:1px solid #dfe3ec;border-radius:19px;margin-bottom:17px}.privacycard h3{margin:0 0 8px;font-size:19px;letter-spacing:-.4px}.privacycard p{margin:0;color:#69738b;font-size:15px;line-height:1.55}.flow{display:flex;gap:16px;align-items:center;justify-content:space-between;margin:28px 0}.node{background:#f1f3fa;border:1px solid #e1e4ed;border-radius:16px;padding:24px 16px;font-size:16px;font-weight:700;text-align:center;flex:1}.node small{display:block;font-size:12px;color:#7b859f;font-weight:400;margin-top:9px}.arrow{color:#a39be5;font-size:28px}.mint{background:#e0f7ed;border:1px solid #c5ebda;color:#316b58;border-radius:9px;padding:15px 20px;font-size:14px;line-height:1.5}.promo{background:#202743!important;color:white;padding:34px!important}.promo .brand{font-size:15px}.promo .mark{background:#303858}.promo .title{font-size:38px;letter-spacing:-1.7px;line-height:1.06}.promo .title span{color:#aea2ff}.promo .sub{color:#b7bfd6;font-size:13px;margin:13px 0}.promo .footer{font-size:10px;color:#9ba6c5;bottom:22px;left:34px;right:34px}.promo .shaperow{display:flex;gap:17px;font-size:24px}.marquee .title{font-size:79px;letter-spacing:-4px}.marquee .sub{font-size:20px;max-width:700px}.marquee .shaperow{font-size:80px;gap:37px}.marquee .brand{font-size:24px}.marquee .mark{width:52px;height:52px}.marquee .footer{font-size:14px;left:60px;right:60px;bottom:35px}
'''

mark = '<span class="mark"><i></i><i></i><i></i><i></i></span>'
mast = '<div class="mast"><div class="brand">'+mark+'Kahoot AI Solver</div><div class="tag">CHROME EXTENSION</div></div>'
def bar(title):
    return '<div class="browserbar"><b></b><b></b><b></b><small>'+title+'</small></div>'
def frame(mode='normal'):
    return '<iframe class="quizframe" src="quiz.html?mode='+mode+'"></iframe>'
def emit(name, content, n=None, extra='', size=''):
    foot = '<div class="footer"><span>Bring your own API key · Provider charges may apply</span><span class="footnum">'+str(n).zfill(2)+' / 05</span></div>' if n else ''
    (WEB/(name+'.html')).write_text('<!doctype html><html><head><meta charset="utf-8"><title>'+name+'</title><style>'+style+'</style></head><body><main id="asset" class="'+extra+'" style="'+size+'">'+(mast if n else '')+content+foot+'</main></body></html>')

emit('01-overview','''<div class="left"><div class="eyebrow">SCREENSHOT → AI → ANSWER</div><h1 class="title">Your quiz.<br><span>Your AI model.</span></h1><p class="sub">Get an answer suggestion from the<br>question on your screen.</p><div class="pill"><span class="key">Alt + Z</span>Capture. Analyze. See a suggestion.</div><p class="caption">Gemini · OpenAI · Compatible APIs<br>You choose the model. You submit the answer.</p></div><div class="right dark"><div class="darklabel"><span>ANSWER PREVIEW</span><span>EXAMPLE · NORMAL MODE</span></div><div class="browser">'''+bar('Practice quiz · example screen')+frame()+'''</div><div class="legend"><span><b>▲</b> Red</span><span><b>◆</b> Blue</span><span><b>●</b> Yellow</span><span><b>■</b> Green</span><span style="margin-left:auto">AI suggestions can be wrong</span></div></div>''',1)

emit('02-setup','''<div class="left" style="top:160px;width:465px"><div class="eyebrow">START WITH YOUR OWN API</div><h1 class="title">Connect once.<br><span>Choose your<br>models.</span></h1><div class="step"><span class="stepnum">01</span><div><b>Open the AI settings</b>Click the extension icon, then ···.</div></div><div class="step"><span class="stepnum">02</span><div><b>Add an API key</b>Connect Gemini, OpenAI or a compatible API.</div></div><div class="step"><span class="stepnum">03</span><div><b>Save and assign your models</b>Choose a model for each of the three slots.</div></div></div><div style="position:absolute;left:636px;top:116px"><div class="nativebox"><div class="nativewrap"><iframe src="settings.html"></iframe></div></div></div><div class="callout" style="right:52px;top:178px"><strong>Actual settings screen</strong>Keys are empty in this capture.<br>Connect your own account.</div><div class="callout" style="right:52px;top:328px"><strong>Your display preference</strong>A readable answer panel or<br>a compact corner indicator.</div><div class="callout" style="right:52px;top:510px"><strong>Models load from your API</strong>Availability and image support<br>depend on your provider.</div>''',2)

emit('03-controls','''<div style="margin-top:42px"><div class="eyebrow">THREE SHORTCUTS. TWO DISPLAY MODES.</div><h1 class="title" style="font-size:53px">Pick your model. <span>Press your shortcut.</span></h1><p class="sub" style="font-size:16px;max-width:100%;margin:14px 0 0">Alt+Z · Alt+X · Alt+C on Windows & Linux. Use Option on Mac. Popup buttons work too.</p></div><div class="modecols" style="margin-top:24px"><div><div class="modetitle">Normal mode <small>Readable answer panel · 15 seconds</small></div><div class="modebrowser" style="height:355px">'''+frame()+'''</div><div class="caption">A larger panel makes the suggestion easy to read.</div></div><div><div class="modetitle">Compact mode <small>Corner indicator · 8 seconds</small></div><div class="modebrowser" style="height:355px">'''+frame('stealth')+'''</div><div class="caption">14px indicator; visible in screenshots and screen sharing.</div></div></div><div class="shapes"><span>▲ Red · Triangle</span><span>◆ Blue · Diamond</span><span>● Yellow · Circle</span><span>■ Green · Square</span><span>Example screens · You click the answer</span></div>''',3)

emit('04-answer-formats','''<div class="left" style="top:172px;width:427px"><div class="eyebrow">BEYOND A SINGLE COLOR</div><h1 class="title">More ways<br><span>to answer.</span></h1><p class="sub">Suggestions for multiple correct options, typed answers, puzzles and numeric sliders.</p><div class="mint" style="margin-top:33px">Audio or video question?<br>Paste a transcript or captions in settings, then use a popup solve button.</div><p class="caption">No audio recording or video upload.<br>Results depend on visible content and your selected model.</p></div><div class="right formatgrid" style="top:153px;width:635px"><div class="formatcard"><h3>Multiple choice</h3><p>All suggested option colors</p><iframe src="multiple.html"></iframe></div><div class="formatcard"><h3>Typed answer</h3><p>Text shown in the answer panel</p><iframe src="text.html"></iframe></div><div class="formatcard"><h3>Puzzle order</h3><p>A sequence of visible option labels</p><iframe src="order.html"></iframe></div><div class="formatcard"><h3>Numeric slider</h3><p>A suggested number</p><iframe src="number.html"></iframe></div><div class="caption" style="grid-column:span 2;margin:0">Actual answer-panel renderer · Example outputs · AI accuracy is not guaranteed</div></div>''',4)

emit('05-data-and-cost','''<div class="left" style="top:172px;width:465px"><div class="eyebrow">KNOW WHAT YOU CONNECT</div><h1 class="title">Your key.<br><span>Your provider.</span></h1><p class="sub">Connect your own API account.<br>Screenshot requests go directly<br>to the provider you select.</p><div class="pill">No developer backend</div><p class="caption" style="margin-top:27px">For learning and practice.<br>Use only where AI assistance is allowed.</p></div><div class="right" style="top:159px;width:609px"><div class="privacycard"><h3>Direct screenshot requests</h3><div class="flow"><div class="node">Your browser<small>Visible tab screenshot</small></div><span class="arrow">→</span><div class="node">Selected API<small>Gemini · OpenAI · Compatible API</small></div></div><p>Screenshots and optional context are sent when you run a solve. Your provider's data policy applies.</p></div><div class="privacycard"><h3>Settings stay in your browser</h3><p>API keys, selected models and display preferences are stored locally. Optional media context is not saved.</p></div><div class="privacycard"><h3>Bring your own key</h3><p>No API key or AI credits are included.<br>Your provider may charge for API usage.</p></div></div>''',5)

emit('promo-small','''<div class="brand">'''+mark+'''Kahoot AI Solver</div><h1 class="title" style="margin-top:27px">Your quiz.<br><span>Your AI model.</span></h1><div class="shaperow" style="position:absolute;right:34px;top:111px;display:grid;grid-template-columns:1fr 1fr;gap:15px"><span style="color:#fb627d">▲</span><span style="color:#69abff">◆</span><span style="color:#ffcf58">●</span><span style="color:#64d8a4">■</span></div><p class="sub">AI answer suggestions for quiz practice.</p><div class="footer"><span>Gemini · OpenAI · Compatible APIs</span><span>Your API key required</span></div>''',extra='promo',size='width:440px;height:280px')
emit('promo-marquee','''<div class="brand">'''+mark+'''Kahoot AI Solver</div><div style="margin-top:52px"><div class="eyebrow" style="color:#c0b7ff">SCREENSHOT → AI → ANSWER</div><h1 class="title">Your quiz.<br><span>Your AI model.</span></h1><p class="sub">AI answer suggestions. Three shortcuts. Your choice of provider.</p></div><div class="shaperow" style="position:absolute;right:124px;top:168px;display:grid;grid-template-columns:1fr 1fr;gap:43px 60px"><span style="color:#fb627d">▲</span><span style="color:#69abff">◆</span><span style="color:#ffcf58">●</span><span style="color:#64d8a4">■</span></div><div class="footer"><span>Gemini · OpenAI · Compatible APIs</span><span>Bring your own API key · Provider charges may apply</span></div>''',extra='promo marquee',size='width:1400px;height:560px;padding:45px 60px!important')

package = OUT / 'kahoot-ai-solver-1.4.0.zip'
files = ['manifest.json','background.js','models.js','content.js','popup.html','popup.js','styles.css','icon16.png','icon48.png','icon128.png']
with zipfile.ZipFile(package,'w',zipfile.ZIP_DEFLATED) as z:
    for name in files:
        z.write(ROOT/name,name)
assert len(json.loads((ROOT/'manifest.json').read_text())['description']) <= 132
print('Built artwork source and', package)
